export const API_END_POINT = {
	API_TASK_GET_ALL:"" ,
	API_PROJECT_GET_ALL: "",
	API_PROJECT_SAVE: "",
	API_LOGIN: "",
	API_CURRENT_USER: "",
	API_CUSTOMER_GET_ALL: "",
	API_GET_MEMBER: "",
	API_GET_FILTER_BRANCH: "",
	API_GET_BY_ID: "",
	API_DELETE_BY_ID: ""
};
